// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ5jE28LoOM3SD9HWPHtG9M_0EgS3EDJY',
    appId: '1:25153457530:web:3ff9f63bf869dd851f1ac3',
    messagingSenderId: '25153457530',
    projectId: 'chatflutter-b4bb0',
    authDomain: 'chatflutter-b4bb0.firebaseapp.com',
    storageBucket: 'chatflutter-b4bb0.appspot.com',
    measurementId: 'G-G9W2C6BZV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5ICVauh9QxlZKq2WC_zLy0ghlzF_O18',
    appId: '1:25153457530:android:374432ea2b1e81a81f1ac3',
    messagingSenderId: '25153457530',
    projectId: 'chatflutter-b4bb0',
    storageBucket: 'chatflutter-b4bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWanzQEr60i1DsVHX4xqQ-B6jHuHXeKWY',
    appId: '1:25153457530:ios:1aaa3c88b9dd31a01f1ac3',
    messagingSenderId: '25153457530',
    projectId: 'chatflutter-b4bb0',
    storageBucket: 'chatflutter-b4bb0.appspot.com',
    iosClientId: '25153457530-2e1a3nigm5a5f0jnhlcq5ksqi8fmeoso.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercrossfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWanzQEr60i1DsVHX4xqQ-B6jHuHXeKWY',
    appId: '1:25153457530:ios:1aaa3c88b9dd31a01f1ac3',
    messagingSenderId: '25153457530',
    projectId: 'chatflutter-b4bb0',
    storageBucket: 'chatflutter-b4bb0.appspot.com',
    iosClientId: '25153457530-2e1a3nigm5a5f0jnhlcq5ksqi8fmeoso.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttercrossfirebase',
  );
}
