// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7LZz1IndMgqBPaoKlSXLFO9gu5o91AWU',
    appId: '1:34248156766:web:d2eee7b05db65f07a076cf',
    messagingSenderId: '34248156766',
    projectId: 'chat-flash-51b4a',
    authDomain: 'chat-flash-51b4a.firebaseapp.com',
    storageBucket: 'chat-flash-51b4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFFZY5-UEHm4f5pIlRvsH5qU8O2lYnj8',
    appId: '1:34248156766:android:78356d3c1cc4d5d2a076cf',
    messagingSenderId: '34248156766',
    projectId: 'chat-flash-51b4a',
    storageBucket: 'chat-flash-51b4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUqBGa-i2lZp8Sigpgop_rcKLWJzNBbc',
    appId: '1:34248156766:ios:5109382dbeab585aa076cf',
    messagingSenderId: '34248156766',
    projectId: 'chat-flash-51b4a',
    storageBucket: 'chat-flash-51b4a.appspot.com',
    iosClientId: '34248156766-lrms00kv1ilt5t7kfdghigr4av9baspr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytrychat',
  );
}
